import React, { useState } from 'react';
import type { SEOAuditResult } from '../types/seo';
import { X, Download, Printer, Copy, Check, FileText } from 'lucide-react';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  auditResult: SEOAuditResult;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  auditResult,
}) => {
  const [copied, setCopied] = useState(false);
  if (!isOpen) return null;

  const { url, metrics, aiEvaluation, timestamp } = auditResult;

  const generateMarkdownReport = () => {
    return `# RankPulse SEO Audit Report: ${url}
Generated: ${new Date(timestamp).toUTCString()}
Overall SEO Score: ${aiEvaluation.overallScore}/100 (Grade ${aiEvaluation.scoreGrade})

## Executive Summary
${aiEvaluation.executiveSummary}

## Category Scores
- On-Page SEO: ${aiEvaluation.categoryScores.onPage.score}/100 (${aiEvaluation.categoryScores.onPage.status})
- Technical SEO: ${aiEvaluation.categoryScores.technical.score}/100 (${aiEvaluation.categoryScores.technical.status})
- Content Quality: ${aiEvaluation.categoryScores.content.score}/100 (${aiEvaluation.categoryScores.content.status})
- Social & Rich Media: ${aiEvaluation.categoryScores.socialAndRich.score}/100 (${aiEvaluation.categoryScores.socialAndRich.status})
- Mobile & Performance: ${aiEvaluation.categoryScores.mobileAndUx.score}/100 (${aiEvaluation.categoryScores.mobileAndUx.status})

## Raw Page Telemetry
- Final Target URL: ${metrics.finalUrl}
- HTTPS Active: ${metrics.isHttps ? 'Yes' : 'No'}
- Latency (TTFB): ${metrics.responseTimeMs}ms
- Page Weight: ${(metrics.pageSizeBytes / 1024).toFixed(1)} KB
- Title Tag: "${metrics.title.text}" (${metrics.title.length} characters)
- Meta Description: "${metrics.metaDescription.text}" (${metrics.metaDescription.length} characters)
- Word Count: ${metrics.content.wordCount.toLocaleString()} words
- H1 Headings: ${metrics.headings.h1.length} found
- Images Missing Alt: ${metrics.images.missingAlt} of ${metrics.images.total}
- Schema.org Types Detected: ${metrics.structuredData.schemaTypes.join(', ') || 'None'}

## Prioritized Actionable Recommendations
${aiEvaluation.recommendations
  .map(
    (rec, i) => `
### ${i + 1}. [${rec.severity.toUpperCase()}] ${rec.title}
- **Impact**: ${rec.impact} | **Effort**: ${rec.effort}
- **Why It Matters**: ${rec.whyItMatters}
- **How to Fix**: ${rec.howToFix}
${rec.codeSnippet ? `\`\`\`html\n${rec.codeSnippet}\n\`\`\`` : ''}
`
  )
  .join('\n')}

---
*Report generated by RankPulse AI SEO Engine.*
`;
  };

  const downloadMarkdown = () => {
    const md = generateMarkdownReport();
    const blob = new Blob([md], { type: 'text/markdown' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `RankPulse_SEO_Audit_${new URL(metrics.finalUrl).hostname}_${Date.now()}.md`;
    link.click();
    URL.revokeObjectURL(link.href);
  };

  const copyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between no-print">
          <div className="flex items-center gap-2.5">
            <FileText className="h-5 w-5 text-emerald-400" />
            <div>
              <h3 className="text-base font-bold text-white">SEO Audit Report & Export</h3>
              <p className="text-xs text-slate-400 font-mono truncate max-w-md">{url}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={copyMarkdown}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={downloadMarkdown}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download .md</span>
            </button>

            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-950 bg-emerald-400 hover:bg-emerald-300 rounded-lg transition-colors"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-200 rounded-lg hover:bg-slate-800 transition-colors ml-2"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Report Content Body */}
        <div className="p-6 md:p-8 overflow-y-auto space-y-6 text-slate-200 text-xs md:text-sm">
          {/* Executive Header Banner */}
          <div className="p-6 rounded-xl bg-slate-950 border border-slate-800 flex items-center justify-between">
            <div className="space-y-1">
              <span className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">RankPulse SEO Inspection</span>
              <h2 className="text-xl font-bold text-white font-mono">{metrics.finalUrl}</h2>
              <span className="text-xs text-slate-400">Scanned on {new Date(timestamp).toLocaleString()}</span>
            </div>

            <div className="text-right font-mono">
              <span className="text-3xl font-extrabold text-emerald-400 tabular-nums">
                {aiEvaluation.overallScore}
              </span>
              <span className="text-xs text-slate-400 block uppercase">Grade {aiEvaluation.scoreGrade}</span>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider font-mono">Executive Summary</h4>
            <p className="text-slate-300 leading-relaxed bg-slate-950/60 p-4 rounded-xl border border-slate-800/80">
              {aiEvaluation.executiveSummary}
            </p>
          </div>

          {/* Category Scores */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider font-mono">Subscore Breakdown</h4>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 text-center font-mono">
              {Object.entries(aiEvaluation.categoryScores).map(([key, val]) => (
                <div key={key} className="p-3 rounded-lg bg-slate-950 border border-slate-800">
                  <span className="text-[10px] text-slate-400 uppercase block truncate">{key}</span>
                  <span className="text-base font-bold text-emerald-400 tabular-nums">{val.score}/100</span>
                </div>
              ))}
            </div>
          </div>

          {/* Recommendations checklist */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider font-mono">
              Actionable Recommendations ({aiEvaluation.recommendations.length})
            </h4>
            <div className="space-y-2">
              {aiEvaluation.recommendations.map((rec, i) => (
                <div key={rec.id} className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1.5">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-emerald-400 font-bold">{i + 1}.</span>
                    <span className="font-semibold text-white">{rec.title}</span>
                    <span className="text-[10px] font-mono text-slate-500">[{rec.severity.toUpperCase()}]</span>
                  </div>
                  <p className="text-xs text-slate-400 pl-5">{rec.whyItMatters}</p>
                  <p className="text-xs text-slate-300 pl-5 font-mono">{rec.howToFix}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
